--● AdminRecordDAO

-- ▷ bookList 여행책 리스트
SELECT B.BOOK_NUM, B.BCATEGORY_NUM, B.BOOK_TITLE, B.BOOK_COMMENT
, B.BOOK_DATE, B.BOOK_REDATE, BOOK_HIT
, ( SELECT USER_NAME
    FROM USERS
    WHERE B.SIGN_NUM = SIGN_NUM 
   ) AS USER_NAME
,NVL((
    SELECT CASE WHEN (STATUS_NUM = 0) OR (STATUS = 1)  THEN '○'
    ELSE 'Ⅹ' END AS BLIND
    FROM VIEW_REPORTLIST
    WHERE TYPE='book' AND CANCEL_NUM IS NULL
    AND ARTICLE = B.BOOK_NUM
    )
 , 'Ⅹ') AS BLINE
FROM BOOK B
ORDER BY B.BOOK_NUM;


-- ▷ cardList 공개된 여행카드 리스트
SELECT C.CARD_NUM, C.CARD_LOCATION
, NVL(( SELECT CASE WHEN CANCEL_NUM IS NULL THEN '○' 
                WHEN CANCEL_NUM IS NOT NULL THEN 'Ⅹ' ELSE 'Ⅹ' END AS BLIND
    FROM VIEW_REPORTLIST
    WHERE TYPE = 'card'
    AND C.CARD_NUM = ARTICLE
   ), 'Ⅹ') AS BLIND
, NVL(C.CARD_BUDGET, 0) AS CARD_BUDGET
, ( SELECT USER_NAME
    FROM USERS
    WHERE C.SIGN_NUM = SIGN_NUM 
   ) AS USER_NAME
, TO_DATE(C.CARD_DATE, 'YYYY-MM-DD') AS CARD_DATE
FROM CARD C
WHERE C.OPEN_NUM = 1 AND C.CARD_DATE IS NOT NULL
ORDER BY C.CARD_NUM;


-- ▷ commentList 댓글 리스트
SELECT V.COMMENT_NUM, V.COMMENT_CONTENT, COMMENT_DATE
,NVL((SELECT CASE WHEN (STATUS_NUM = 0) OR (STATUS = 1)  THEN '○'
    ELSE 'Ⅹ' END AS BLIND
    FROM VIEW_REPORTLIST
    WHERE TYPE='comment' AND CANCEL_NUM IS NULL
    AND ARTICLE = V.COMMENT_NUM
), 'Ⅹ') AS BLINE
FROM VIEW_COMMENTLIST V
WHERE SIGN_NUM = 124
ORDER BY COMMENT_NUM;

-- ▷ bookTitleSearchList 여행책 제목 검색 리스트 조회
SELECT B.BOOK_NUM, B.BCATEGORY_NUM, B.BOOK_TITLE, B.BOOK_COMMENT
, B.BOOK_DATE, B.BOOK_REDATE, BOOK_HIT
, ( SELECT USER_NAME
    FROM USERS
    WHERE B.SIGN_NUM = SIGN_NUM 
   ) AS USER_NAME
,NVL((
    SELECT CASE WHEN (STATUS_NUM = 0) OR (STATUS = 1)  THEN '○'
    ELSE 'Ⅹ' END AS BLIND
    FROM VIEW_REPORTLIST
    WHERE TYPE='book' AND CANCEL_NUM IS NULL
    AND ARTICLE = B.BOOK_NUM
    )
 , 'Ⅹ') AS BLINE
FROM BOOK B
WHERE BOOK_TITLE LIKE '%한%'
ORDER BY B.BOOK_NUM;


-- ▷ cardTitleSearchList 여행카드 제목(장소명) 검색 리스트 조회
SELECT C.CARD_NUM, C.CARD_LOCATION
, NVL(( SELECT CASE WHEN CANCEL_NUM IS NULL THEN '○' 
                WHEN CANCEL_NUM IS NOT NULL THEN 'Ⅹ' ELSE 'Ⅹ' END AS BLIND
    FROM VIEW_REPORTLIST
    WHERE TYPE = 'card'
    AND C.CARD_NUM = ARTICLE
   ), 'Ⅹ') AS BLIND
, NVL(C.CARD_BUDGET, 0) AS CARD_BUDGET
, ( SELECT USER_NAME
    FROM USERS
    WHERE C.SIGN_NUM = SIGN_NUM 
   ) AS USER_NAME
, TO_DATE(C.CARD_DATE, 'YYYY-MM-DD') AS CARD_DATE
FROM CARD C
WHERE C.OPEN_NUM = 1 AND C.CARD_DATE IS NOT NULL
AND C.CARD_LOCATION LIKE '%남산%'
ORDER BY C.CARD_NUM;


-- ▷ bookNicknameSearchList 여행책 작성자 검색 리스트 조회
SELECT B.BOOK_NUM, B.BCATEGORY_NUM, B.BOOK_TITLE, B.BOOK_COMMENT
, B.BOOK_DATE, B.BOOK_REDATE, BOOK_HIT
, ( SELECT USER_NAME
    FROM USERS
    WHERE B.SIGN_NUM = SIGN_NUM 
   ) AS USER_NAME
,NVL((
    SELECT CASE WHEN (STATUS_NUM = 0) OR (STATUS = 1)  THEN '○'
    ELSE 'Ⅹ' END AS BLIND
    FROM VIEW_REPORTLIST
    WHERE TYPE='book' AND CANCEL_NUM IS NULL
    AND ARTICLE = B.BOOK_NUM
    )
 , 'Ⅹ') AS BLINE
FROM BOOK B, USERS U
WHERE B.SIGN_NUM = U.SIGN_NUM
AND U.USER_NAME LIKE '%나%'
ORDER BY B.BOOK_NUM;


-- ▷ cardNicknameSearchList 여행카드 작성자 검색 리스트 조회
SELECT CARD_NUM, CARD_LOCATION, BLIND, CARD_BUDGET, USER_NAME, CARD_DATE
FROM 
(SELECT C.CARD_NUM, C.CARD_LOCATION
, NVL(( SELECT CASE WHEN CANCEL_NUM IS NULL THEN '○' 
                WHEN CANCEL_NUM IS NOT NULL THEN 'Ⅹ' ELSE 'Ⅹ' END AS BLIND
    FROM VIEW_REPORTLIST
    WHERE TYPE = 'card'
    AND C.CARD_NUM = ARTICLE
   ), 'Ⅹ') AS BLIND
, NVL(C.CARD_BUDGET, 0) AS CARD_BUDGET
, ( SELECT USER_NAME
    FROM USERS 
    WHERE C.SIGN_NUM = SIGN_NUM 
   ) AS USER_NAME
, TO_DATE(C.CARD_DATE, 'YYYY-MM-DD') AS CARD_DATE
FROM CARD C
WHERE C.OPEN_NUM = 1 AND C.CARD_DATE IS NOT NULL
) T
WHERE T.USER_NAME LIKE '%고%'
ORDER BY T.CARD_NUM;

-- ▷ bookSearch 여행책 번호로 여행책 조회 (열람)
SELECT B.BOOK_NUM, B.BCATEGORY_NUM, B.BOOK_TITLE, B.BOOK_COMMENT
, B.BOOK_DATE, B.BOOK_REDATE, BOOK_HIT
, ( SELECT USER_NAME
    FROM USERS
    WHERE B.SIGN_NUM = SIGN_NUM 
   ) AS USER_NAME
,NVL((
    SELECT CASE WHEN (STATUS_NUM = 0) OR (STATUS = 1)  THEN '○'
    ELSE 'Ⅹ' END AS BLIND
    FROM VIEW_REPORTLIST
    WHERE TYPE='book' AND CANCEL_NUM IS NULL
    AND ARTICLE = B.BOOK_NUM
    )
 , 'Ⅹ') AS BLINE
FROM BOOK B
WHERE BOOK_NUM = 5
ORDER BY B.BOOK_NUM;


-- ▷ cardSearch 여행카드 번호로 여행카드 조회
-- 카드 상세 열람
SELECT CARD_NUM, SIGN_NUM, CARD_LAT, CARD_LNG, CARD_ZIPCODE, CARD_ADDRESS, CARD_SADDRESS, CARD_LOCATION
, CARD_BUDGET, CARD_COMMENT, CARD_IMG1, CARD_IMG2, CARD_IMG3, TO_DATE(CARD_VISITDATE, 'YYYY-MM-DD') AS CARD_VISIDAE
, TO_DATE(CARD_DATE, 'YYYY-MM-DD') AS CARD_DATE
FROM CARD
WHERE CARD_NUM = 5;

-- ▷ bReportStatusInsert 여행책 경고 처리를 위해 신고 처리 테이블에 신규 등록 (겹침)
INSERT INTO BREPORT_STATUS(BSTATUS_NUM, ADMIN_NUM, BSTATUS_DATE, BREPORT_NUM, TYPE_NUM, BSTATUS_CHECK)
VALUES(BREPORT_STATUS_SEQ.NEXTVAL, 1, TO_DATE(SYSDATE, 'YYYY-MM-DD'), 1, 1, NULL);

-- ▷ cReportStatusInsert 여행카드 경고 처리를 위해 신고 처리 테이블에 신규 등록 (겹침)
INSERT INTO CREPORT_STATUS(CSTATUS_NUM, ADMIN_NUM, CSTATUS_DATE, CREPORT_NUM, TYPE_NUM, CSTATUS_CHECK)
VALUES(CREPORT_STATUS_SEQ.NEXTVAL, 1, TO_DATE(SYSDATE, 'YYYY-MM-DD'), 1, 1, NULL);
