--● AdminReportDAO

SELECT *
FROM VIEW_REPORTLIST;

-- ▷ list 신고 내역 리스트(여행책,여행카드,댓글)
SELECT REPORT_NUM, REPORT_TITLE, WRITER, REPORT_DATE
, CASE WHEN STATUS_NUM IS NULL THEN '처리전' 
       ELSE '처리완료' END AS STATUS_STATE 
, CASE WHEN CANCEL_NUM IS NULL THEN '블라인드'
       ELSE '경고해제' END AS BLIND
FROM VIEW_REPORTLIST
WHERE TYPE = 'book';

-- ▷ searchList 제목 키워드로 신고 리스트 조회(여행책,여행카드,댓글)
SELECT TYPE, REPORT_NUM, REPORT_TITLE, WRITER, REPORT_DATE
, CASE WHEN STATUS_NUM IS NULL THEN '처리전' 
       ELSE '처리완료' END AS STATUS_STATE 
, CASE WHEN CANCEL_NUM IS NULL THEN '블라인드'
       ELSE '경고해제' END AS BLIND
FROM VIEW_REPORTLIST
WHERE REPORT_TITLE LIKE '%홍보%'
AND TYPE = 'book';


-- ▷ search 신고 번호로 신고 내역 조회(여행책,여행카드,댓글)
SELECT TYPE, REPORT_NUM, REPORT_TITLE, WRITER, REPORT_DATE
, CASE WHEN STATUS_NUM IS NULL THEN '처리전' 
       ELSE '처리완료' END AS STATUS_STATE 
, CASE WHEN CANCEL_NUM IS NULL THEN '블라인드'
       ELSE '경고해제' END AS BLIND
FROM VIEW_REPORTLIST
WHERE REPORT_NUM = 1
AND TYPE = 'book';


-- ▷ bStatusUpdate 회원의 책 신고를 처리완료로 만들어주는 작업 (겹침) → 경고하기랑 같은 기능
INSERT INTO BREPORT_STATUS(BSTATUS_NUM, ADMIN_NUM, BSTATUS_DATE, BREPORT_NUM, TYPE_NUM, BSTATUS_CHECK)
VALUES(BREPORT_STATUS_SEQ.NEXTVAL, 1, TO_DATE(SYSDATE, 'YYYY-MM-DD'), 1, 1, NULL);

-- ▷ cStatusUpdate 회원의 카드 신고를 처리완료로 만들어주는 작업 (겹침) → 경고하기랑 같은 기능
INSERT INTO CREPORT_STATUS(CSTATUS_NUM, ADMIN_NUM, CSTATUS_DATE, CREPORT_NUM, TYPE_NUM, CSTATUS_CHECK)
VALUES(CREPORT_STATUS_SEQ.NEXTVAL, 1, TO_DATE(SYSDATE, 'YYYY-MM-DD'), 1, 1, NULL);


-- ▷ coStatusUpdate 회원의 댓글 신고를 처리완료로 만들어주는 작업
INSERT INTO COREPORT_STATUS(COSTATUS_NUM, ADMIN_NUM, COSTATUS_DATE, COREPORT_NUM, TYPE_NUM, COSTATUS_CHECK)
VALUES(CREPORT_STATUS_SEQ.NEXTVAL, 1, TO_DATE(SYSDATE, 'YYYY-MM-DD'), 1, 1, NULL);

-- ▷ bCancelInsert 책에 준 경고를 해제하기 위한 작업  
INSERT INTO BWARNING_CANCEL(BCANCEL_NUM, ADMIN_NUM, BSTATUS_NUM, REASON_NUM, BCANCEL_MEMO)
VALUES(BWARNING_SEQ.NEXTVAL, 1, 1, 1, '');

-- 경고해제 된 신고처리 번호 검색
SELECT BSTATUS_NUM
FROM BWARNING_CANCEL
WHERE BCANCEL_NUM = 5;

-- ▷ cCancelInsert 카드에 준 경고를 해제하기 위한 작업
INSERT INTO CWARNING_CANCEL(CCANCEL_NUM, ADMIN_NUM, CSTATUS_NUM, REASON_NUM, CCANCEL_MEMO)
VALUES(CWARNING_SEQ.NEXTVAL, 1, 1, 1, '');

-- 경고해제 된 신고처리 번호 검색
SELECT CSTATUS_NUM
FROM CWARNING_CANCEL
WHERE CCANCEL_NUM = 5;


-- ▷ coCancelInsert 댓글에 준 경고를 해제하기 위한 작업
INSERT INTO COWARNING_CANCEL(COCANCEL_NUM, ADMIN_NUM, COSTATUS_NUM, REASON_NUM, COCANCEL_MEMO)
VALUES(COWARNING_SEQ.NEXTVAL, 1, 1, 1, '');
