-- 뷰 생성 여행책리스트
CREATE OR REPLACE VIEW VIEW_BOOKLIST
AS
SELECT B.BOOK_NUM AS BOOK_NUM, TC.TCATEGORY_NAME AS BCATEGORY_NUM, B.BOOK_TITLE AS BOOK_TITLE, B.BOOK_DATE AS BOOK_DATE, B.BOOK_HIT AS BOOK_HIT, B.SIGN_NUM AS SIGN_NUM, U.USER_NAME AS USER_NAME, B.BOOK_COMMENT AS BOOK_COMMENT
FROM BOOK B, TRAVEL_CATEGORY TC, USERS U
WHERE B.BCATEGORY_NUM = TC.TCATEGORY_NUM
    AND B.SIGN_NUM = U.SIGN_NUM;

-- 뷰 생성 좋아요리스트
CREATE OR REPLACE VIEW VIEW_LIKELIST
AS
SELECT B.BOOK_NUM AS BOOK_NUM, B.BOOK_TITLE AS BOOK_TITLE, B.SIGN_NUM AS WRITER, L.SIGN_NUM AS LIKER, U.USER_NAME AS LIKER_NAME, L.LIKED_NUM AS LIKED_NUM, L.LIKED_DATE AS LIKED_DATE
FROM BOOK B, LIKED L, USERS U
WHERE B.BOOK_NUM = L.BOOK_NUM
    AND L.SIGN_NUM = U.SIGN_NUM;    

-- 뷰 생성 댓글리스트
CREATE OR REPLACE VIEW VIEW_COMMENTLIST
AS
SELECT C.COMMENT_NUM AS COMMENT_NUM, C.COMMENT_DATE AS COMMENT_DATE, C.COMMENT_CONTENT COMMENT_CONTENT, B.BOOK_NUM AS BOOK_NUM, U.SIGN_NUM AS SIGN_NUM, U.USER_NAME AS USER_NAME
FROM COMMENTS C, BOOK B, USERS U, BOOKED_COMMENT BC
WHERE C.SIGN_NUM = U.SIGN_NUM
    AND C.COMMENT_NUM = BC.COMMENT_NUM
    AND BC.BOOK_NUM = B.BOOK_NUM;

-- 뷰생성 관리자 자주 묻는 질문 리스트 
CREATE OR REPLACE VIEW VIEW_FAQLIST
AS
SELECT F.FAQ_NUM AS FAQ_NUM, F.QCATEGORY_NUM AS QCATEGORY_NUM, F.ADMIN_NUM AS ADMIN_NUM, F.FAQ_QUESTION AS FAQ_QUESTION, F.FAQ_ANSWER AS FAQ_ANSWER, F.FAQ_DATE AS FAQ_DATE, QC.QCATEGORY_CLASS AS QCATEGORY_CLASS
FROM FAQ F, QUESTION_CATEGORY QC
WHERE F.QCATEGORY_NUM = QC.QCATEGORY_NUM;


-- 뷰 생성 관리자 질문 답변 리스트
CREATE OR REPLACE VIEW VIEW_QNA
AS
SELECT Q.QUESTION_NUM AS QUESTION_NUM, QC.QCATEGORY_NUM AS QCATEGORY_NUM, QC.QCATEGORY_CLASS AS QCATEGORY_CLASS, Q.QUESTION_TITLE AS QUESTION_TITLE, Q.SIGN_NUM AS SIGN_NUM, Q.QUESTION_DATE AS QUESTION_DATE
     , NVL(A.ANSWER_NUM, 0) AS ANSWER_NUM, A.ANSWER_DATE AS ANSWER_DATE, A.ANSWER_CHECK AS ANSWER_CHECK
FROM ANSWER A  RIGHT JOIN QUESTION Q
    ON A.QUESTION_NUM = Q.QUESTION_NUM
	LEFT JOIN QUESTION_CATEGORY QC
	ON Q.QCATEGORY_NUM = QC.QCATEGORY_NUM;

-- 뷰 생성  관리자 질문 뷰 (답변 없을 때)
CREATE OR REPLACE VIEW VIEW_QUESTION
AS
SELECT Q.QUESTION_NUM AS QUESTION_NUM, Q.QCATEGORY_NUM AS QCATEGORY_NUM, QC.QCATEGORY_CLASS AS QCATEGORY_CLASS, Q.SIGN_NUM AS SIGN_NUM, U.USER_NAME AS USER_NAME, Q.QUESTION_DATE AS QUESTION_DATE, Q.QUESTION_TITLE AS QUESTION_TITLE, Q.QUESTION_CONTENT AS QUESTION_CONTENT
FROM QUESTION Q, QUESTION_CATEGORY QC, USERS U
WHERE Q.QCATEGORY_NUM = QC.QCATEGORY_NUM
	AND Q.SIGN_NUM = U.SIGN_NUM;

-- 뷰 생성  관리자 질문답변 뷰 (답변 있을 때)
CREATE OR REPLACE VIEW VIEW_ANSWER
AS
SELECT VQ.QUESTION_NUM AS QUESTION_NUM, VQ.QCATEGORY_NUM AS QCATEGORY_NUM, VQ.QCATEGORY_CLASS AS QCATEGORY_CLASS, VQ.SIGN_NUM AS SIGN_NUM, VQ.USER_NAME AS USER_NAME, VQ.QUESTION_DATE AS QUESTION_DATE, VQ.QUESTION_TITLE AS QUESTION_TITLE, VQ.QUESTION_CONTENT AS QUESTION_CONTENT, A.ANSWER_NUM AS ANSWER_NUM, A.ANSWER_DATE AS ANSWER_DATE, A.ANSWER_CONTENT AS ANSWER_CONTENT, AD.ADMIN_NUM AS ADMIN_NUM, AD.ADMIN_NAME AS ADMIN_NAME 
FROM VIEW_QUESTION VQ, ANSWER A, ADMIN AD
WHERE VQ.QUESTION_NUM = A.QUESTION_NUM
    AND A.ADMIN_NUM = AD.ADMIN_NUM;